version: '3'
services:
  db:
    image: mysql:8.0.33
    env_file: docker.env
    ports:
      - "3306:3306"

  web:
    build: .
    ports:
      - "8080:8080"
    env_file: docker.env
    depends_on:
      - db
